apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: timescaledb-single
  namespace: ldl-timescale-ns
spec:
  releaseName: timescaledb-single
  chart:
    spec:
      chart: timescaledb-single
      version: "0.27.3"
      sourceRef:
        kind: HelmRepository
        name: timescaledb-single
        namespace: ldl-timescale-ns
  interval: 1h0m0s
  install:
    remediation:
      retries: 1
  values:
    replicaCount: 1
    persistentVolumes:
      data:
        storageClass: "ase-node-local"
      wal:
        enabled: false
