apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: timescaledb-single
  namespace: ldl-timescale-ns
spec:
  interval: 5m0s
  url: https://charts.timescale.com/
